---
- include_tasks: '{{ include_yml }}'
  loop_control:
    loop_var: include_yml
  with_first_found:
    - files:
      - '{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml'
      skip: false
