---
- name: Set kernel parameters
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: present
    sysctl_file: /etc/sysctl.d/haproxy.conf
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: 'net.ipv4.tcp_fin_timeout', value: '30' }
    - { name: 'net.ipv4.tcp_keepalive_time', value: '1200' }
    - { name: 'net.ipv4.tcp_keepalive_probes', value: '6' }
    - { name: 'net.ipv4.tcp_keepalive_intvl', value: '30' }
    - { name: 'net.ipv4.tcp_max_syn_backlog', value: '4096' }
    - { name: 'net.ipv4.tcp_max_tw_buckets', value: '55036' }
    - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
    - { name: 'net.ipv4.ip_local_port_range', value: '1024 65535' }
    - { name: 'net.core.somaxconn', value: '4096' }
    - { name: 'net.core.netdev_max_backlog', value: '4096' }
    - { name: 'fs.file-max', value: '60000' }
