---
- name: Install ClamAV package
  yum:
    name: "{{ item.name }}"
    state: present
    releasever: "{{ ansible_distribution_version }}"
  loop:
    - { name: epel-release }
    - { name: clamav }
    - { name: clamav-scanner-systemd }
    - { name: clamav-update }
