---
ntpservers: "{{ '192.168.137.5,0x8 192.168.137.6,0x8' if (inventory_hostname == 'ad-01') else '192.168.137.5,0xa 192.168.137.6,0xa' }}"
synctype: "{{ 'NTP' if (inventory_hostname == 'ad-01') else 'AllSync' }}"
