---
 - name: "Set ntp server"
   win_regedit:
     path: 'HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Parameters'
     name: 'NtpServer'
     data: '192.168.137.5,0x8'
     type: string
   notify: Restart w32time
