---
firewalld:
  rules:
    # ssh
    - priority: '1'
      protocol: 'tcp'
      src: '192.168.137.0/24'
      port: '22'
    - priority: '1'
      protocol: 'tcp'
      src: '192.168.138.0/24'
      port: '22'
    # rsyslog
    - priority: '1'
      protocol: 'tcp'
      src: '192.168.137.0/24'
      port: '514'
    - priority: '1'
      protocol: 'tcp'
      src: '192.168.138.0/24'
      port: '514'
