---
- name: Set coredump system.conf
  ini_file:
    path: /etc/systemd/system.conf
    state: present
    section: Manager
    no_extra_spaces: yes
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop:
    - { option: DumpCore, value: 'yes' }
    - { option: DefaultLimitCORE, value: 'infinity' }
  notify:
    - systemctl daemon-reexec

- name: Set coredump coredump.conf
  ini_file:
    path: /etc/systemd/coredump.conf
    state: present
    section: Coredump
    no_extra_spaces: yes
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  loop:
    - { option: Compress, value: 'no' }
  notify:
    - systemctl daemon-reexec

