---
- name: Deploy sshd_config template
  template:
    src: roles/linux_common/templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify:
    - Restart sshd
