---
- name: Restart php-fpm
  service:
    name: php-fpm
    state: restarted

- name: Restart mysqld
  service:
    name: mysqld
    state: restarted

- name: Restart zabbix-server
  service:
    name: zabbix-server
    state: restarted
